apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-be-egress
  namespace: backend-ns
spec:
  podSelector:
    matchLabels:
      app: bookstore-be
  policyTypes: [Egress]
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: data-ns
    ports:
    - port: 3306
    - port: 6379
