apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-fe-to-be
  namespace: backend-ns
spec:
  podSelector:
    matchLabels:
      app: bookstore-be
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: frontend-ns
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: argocd
      podSelector:
        matchLabels:
          app: bookstore-fe
    ports:
    - protocol: TCP
      port: 3000
