apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-fe-to-be
spec:
  podSelector:
    matchLabels:
      app: bookstore-be
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: bookstore-fe
    ports:
    - protocol: TCP
      port: 3000
