apiVersion: v1
kind: Service
metadata:
  name: bookstore-be-svc
  namespace: backend-ns
spec:
  selector:
    app: bookstore-be
  ports:
  - port: 3000
    targetPort: 3000

  env:
  - name: DB_HOST
    value: bookstore-db.data-ns.svc.cluster.local
