apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-be-to-redis
  namespace: data-ns
spec:
  podSelector:
    matchLabels:
      app: redis
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: backend-ns
      podSelector:
        matchLabels:
          app: bookstore-be
    ports:
    - port: 6379
