apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: data-ns
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: bookstore-sc
  resources:
    requests:
      storage: 5Gi
