apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-fe
  namespace: frontend-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-fe
  template:
    metadata:
      labels:
        app: bookstore-fe
    spec:
      containers:
      - name: bookstore-fe
        image: moelhamzawy1/frontend:v2
        ports:
        - containerPort: 8080
