apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookstore-ingress
  namespace: frontend-ns
spec:
  ingressClassName: nginx
  rules:
  - host: bookstore.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bookstore-fe-svc
            port:
              number: 8080
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: bookstore-be-svc
            port:
              number: 3000
