apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bookstore-db
  namespace: data-ns
spec:
  serviceName: bookstore-db-svc
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-db
  template:
    metadata:
      labels:
        app: bookstore-db
    spec:
      containers:
      - name: mysql
        image: moelhamzawy1/database:v1
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: bookstore-db-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: bookstore-db-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstore-db-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstore-db-secret
              key: MYSQL_ROOT_PASSWORD
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        readinessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "127.0.0.1"]
          initialDelaySeconds: 15
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql




  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: bookstore-sc
      resources:
        requests:
          storage: 10Gi