apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bookstore-db
spec:
  selector:
    matchLabels:
      app: bookstore-db
  serviceName: "bookstore-db-svc"
  replicas: 2
  template:
    metadata:
      labels:
        app: bookstore-db
    spec:
      containers:
      - name: bookstore-db
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi