apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-be-to-db
  namespace: data-ns
spec:
  podSelector:
    matchLabels:
      app: bookstore-db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: backend-ns
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: argocd
      podSelector:
        matchLabels:
          app: bookstore-be
    ports:
    - protocol: TCP
      port: 3306
