apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-db-ingress
  namespace: data-ns
spec:
  podSelector:
    matchLabels:
      app: bookstore-db
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: backend-ns
    ports:
    - port: 3306
