apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bookstore
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: backend
            path: k8s/backend
            namespace: backend-ns
          - name: frontend
            path: k8s/frontend
            namespace: frontend-ns
          - name: db
            path: k8s/db
            namespace: data-ns
          - name: redis
            path: k8s/redis
            namespace: data-ns

  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ksami13200/openshift-bookstore
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
