apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bookstore-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - app: frontend
        path: k8s/frontend
        namespace: frontend-ns
      - app: backend
        path: k8s/backend
        namespace: backend-ns 
      - app: data

        path: k8s/db
        namespace: data-ns
  template:
    metadata:
      name: '{{app}}-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/your-org/bookstore.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
