apiVersion: v1
kind: Secret
metadata:
  name: bookstore-db-secret
  namespace: data-ns
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=
  MYSQL_PASSWORD: Ym9va3N0b3JlcGFzcw==
  REDIS_PASSWORD: cmVkaXNwYXNz
